name: observer-loki

services:
  gateway:
    image: nginx:1.27.4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3110:80"
      - "3100"
    networks:
      - network-observer-loki

  reader:
    image: &lokiImage grafana/loki:3.3.2
    volumes:
      - data-observer-loki:/etc/loki
      - ./config.yaml:/etc/loki/config.yaml
    # only needed for interactive debugging with dlv
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - apparmor=unconfined
    ports:
      - "3100"
      - "7946"
      # uncomment to use interactive debugging
      # - "40000-40002:40000" # makes the replicas available on ports 40000, 40001, 40002
    command: "-config.file=/etc/loki/config.yaml -target=read -legacy-read-mode=false"
    networks:
      - network-observer-loki
    restart: always
    deploy:
      mode: replicated
      replicas: 2

  writer:
    image: *lokiImage
    volumes:
      - data-observer-loki:/etc/loki
      - ./config.yaml:/etc/loki/config.yaml
    # only needed for interactive debugging with dlv
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - apparmor=unconfined
    ports:
      - "3100"
      - "7946"
      # uncomment to use interactive debugging
      # - "50000-50002:40000" #  makes the replicas available on ports 50000, 50001, 50002
    command: "-config.file=/etc/loki/config.yaml -target=write"
    networks:
      - network-observer-loki
    restart: always
    deploy:
      mode: replicated
      replicas: 2

  backend:
    image: *lokiImage
    volumes:
      - data-observer-loki:/etc/loki
      - ./config.yaml:/etc/loki/config.yaml
      # - ./rules.yaml:/loki/rules:ro
    # only needed for interactive debugging with dlv
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - apparmor=unconfined
    ports:
      - "3100"
      - "7946"
      # uncomment to use interactive debugging
      # - "60000-60002:40000" #  makes the replicas available on ports 60000, 60001, 60002
    command: "-config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false"
    networks:
      - network-observer-loki
    restart: always
    deploy:
      mode: replicated
      replicas: 2


volumes:
  data-observer-loki:

networks:
  network-observer-loki:
    driver: bridge