name: basic

services:

  jaeger-init:
    image: busybox:latest
    volumes:
      - data-basic-jaeger:/data
    command: ["sh", "-c", "mkdir -p /data/values /data/keys && chown -R 1000:1000 /data"]
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - network-basic
    environment:
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/data/value
      - BADGER_DIRECTORY_KEY=/data/key
    volumes:
      - data-basic-jaeger:/data
    user: "1000:1000"
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans
      - "4318:4318" # HTTP OpenTelemetry
      - "4317:4317" # gRPC OpenTelemetry
    deploy:
      restart_policy:
          condition: unless-stopped
    depends_on:
      - jaeger-init

  mongodb:
    image: mongo:latest
    networks:
      - network-basic
    volumes:
      - data-basic-mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypswd123

  app:
    image: ifundeasy/simple-crud:latest
    networks:
      - network-basic
    environment:
      APP_NAME: app
      APP_PORT: "3000"
      OTEL_RPC_URI: jaeger:4317
      EXTERNAL_API: http://app:3000/products
      MONGO_URI: mongodb://root:mypswd123@mongodb:27017
      MONGO_DB_NAME: monitoring
    ports:
      - '4000:3000'
    depends_on:
      - jaeger
      - mongodb

volumes:
  data-basic-jaeger:
    driver: local
  data-basic-mongodb:

networks:
  network-basic:
    driver: bridge