apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-write
  namespace: namespace-3
  labels:
    app: loki
    role: write
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
      role: write
  template:
    metadata:
      labels:
        app: loki
        role: write
    spec:
      containers:
      - name: loki
        image: grafana/loki:3.3.2
        args:
        - -config.file=/etc/loki/loki-config.yaml
        - -target=write
        volumeMounts:
        - name: config
          mountPath: /etc/loki
          readOnly: false
      volumes:
      - name: config
        configMap:
          name: loki-write-config
