apiVersion: v1
kind: ConfigMap
metadata:
  name: app-two-config
  namespace: namespace-2
data:
  APP_NAME: service-two
  APP_PORT: "3000"
  OTEL_RPC_URI: host.docker.internal:4317
  EXTERNAL_API: http://app-one-service.namespace-1.svc.cluster.local:3000/products
  MONGO_URI: mongodb://root:mypswd123@host.docker.internal:27017
  MONGO_DB_NAME: monitoring

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two-deployment
  namespace: namespace-2
  labels:
    app: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
        - name: app-two
          image: ifundeasy/simple-crud:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-two-config

---

apiVersion: v1
kind: Service
metadata:
  name: app-two-service
  namespace: namespace-2
spec:
  selector:
    app: app-two
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32762
  type: NodePort
