name: observability

include:
  - ./optional.yaml
  - ./dependency.yaml
  # - ./grafana.yaml

services:

  app:
    image: ifundeasy/simple-crud:latest
    networks:
      - network-observability
    environment:
      APP_NAME: app
      APP_PORT: "3000"
      OTEL_RPC_URI: jaeger:4317
      EXTERNAL_API: http://app:3000/products
      MONGO_URI: mongodb://root:mypswd123@mongodb:27017
      MONGO_DB_NAME: monitoring
    ports:
      - '4000:3000'
    depends_on:
      - mongodb
