apiVersion: 1
datasources:
  - access: proxy
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "docker"
    name: loki
    type: loki
    uid: loki
    url: http://host.docker.internal:3110
    version: 1

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://host.docker.internal:3200
    basicAuth: false
    isDefault: false
    editable: true
    version: 1
    apiVersion: 1
    uid: tempo
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      streamingEnabled:
        search: true
    secureJsonData:
      httpHeaderValue1: "docker"

  - name: Mimir
    uid: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://host.docker.internal:9009/prometheus
    version: 1
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      alertmanagerUid: "alertmanager"
    secureJsonData:
      httpHeaderValue1: "docker"
    isDefault: false

  - name: Mimir Alertmanager
    uid: alertmanager
    type: alertmanager
    access: proxy
    orgId: 1
    url: http://host.docker.internal:9009/
    version: 1
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      implementation: "cortex"
    secureJsonData:
      httpHeaderValue1: "docker"
