apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-read
  namespace: namespace-3
  labels:
    app: loki
    role: read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
      role: read
  template:
    metadata:
      labels:
        app: loki
        role: read
    spec:
      containers:
      - name: loki
        image: grafana/loki:3.3.2
        args:
        - -config.file=/etc/loki/loki-config.yaml
        - -target=read
        - -legacy-read-mode=false
        volumeMounts:
        - name: config
          mountPath: /etc/loki
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: loki-read-config
