apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: namespace-3
data:
  GF_DATABASE_TYPE: mysql
  GF_DATABASE_HOST: host.docker.internal:3306
  GF_DATABASE_NAME: grafana
  GF_DATABASE_USER: default
  GF_DATABASE_PASSWORD: mypswd123
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin