name: observer-party

services:

  mysql:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: myRootPassword123
      MYSQL_DATABASE: grafana
      MYSQL_USER: default
      MYSQL_PASSWORD: mypswd123
    ports:
      - '3306:3306'
    volumes:
      - data-observer-party-mysql:/var/lib/mysql
    networks:
      - network-observer-party

  localstack:
    image: 'localstack/localstack:4.1.1'
    environment:
      - SERVICES=s3
    ports:
      - '4566:4566'
      # - '4510-4559:4510-4559'
    volumes:
      - data-observer-party-localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    healthcheck:
      test: "bash -c 'AWS_ACCESS_KEY_ID=default AWS_SECRET_ACCESS_KEY=mypswd123 aws --endpoint-url=http://127.0.0.1:4566 s3 ls'"
      retries: 5
      interval: 10s
    networks:
      - network-observer-party

  init-bucket:
    image: amazon/aws-cli
    environment:
      - AWS_ACCESS_KEY_ID=default
      - AWS_SECRET_ACCESS_KEY=mypswd123
      - AWS_DEFAULT_REGION=us-east-1
    restart: no
    entrypoint: 
      - "sh"
      - "-c"
      - |
        sleep 3
        aws --endpoint-url=http://localstack:4566 s3 mb s3://loki-data
        aws --endpoint-url=http://localstack:4566 s3 mb s3://tempo-data
        aws --endpoint-url=http://localstack:4566 s3 mb s3://mimir-data
        aws --endpoint-url=http://localstack:4566 s3 ls

    depends_on:
      - localstack
    networks:
      - network-observer-party
  
  s3-manager:
    image: cloudlena/s3manager:v0.5.0
    ports:
      - 4500:8080
    environment:
      - ENDPOINT=localstack:4566
      - ACCESS_KEY_ID=default
      - SECRET_ACCESS_KEY=mypswd123
      - USE_SSL=false
    depends_on:
      - localstack
    networks:
      - network-observer-party

volumes:
  data-observer-party-mysql:
  data-observer-party-localstack:

networks:
  network-observer-party:
    driver: bridge
